os:
  - linux
  - linux-ppc64le
language: node_js
node_js:
  - "6"
  - "8"
env:
  - CMD=lint
  - CMD=fbjs:build
  - CMD=fbjs:test
  - CMD=fbjs:flow
  - CMD=preset:test
  - CMD=signedsource:test
matrix:
  exclude:
  - os: linux-ppc64le
    env: CMD=fbjs:flow
script: yarn run $CMD
